---
title: "ICRW8_figs"
output: html_notebook
---

Figures for presentation at 2023 ICRW8 conference

```{r SoilMoisture}
soilWaterRaw <- read.csv("Data/KJ_WS1_2019_soil_water.csv")

soilWater <- soilWaterRaw %>% 
  mutate(DT = mdy_hm(datetime)) %>% 
  mutate(wp_kPa_50cm = ifelse(wp_kPa_50cm < -40, -40, wp_kPa_50cm)) %>% 
  mutate(wpMA = rollmean(wp_kPa_50cm, 10, fill = NA))

soilWaterPlot1 <- ggplot(data = soilWater, aes(x = DT, y = wp_kPa_50cm, group = site)) +
  geom_line() +
  labs(
       y = "WP, 50 cm (kPa)")

soilWaterPlot2 <- ggplot(data = soilWater, aes(x = DT, y = vwc_50cm, group = site)) +
  geom_line() +
  labs(
       y = "VWC, 50 cm")

soilWaterPlot3 <- ggplot(data = soilWater, aes(x = DT, y = vwc_100cm, group = site)) +
  geom_line() +
  labs(
       y = "VWC, 100 cm")

soilWaterPlot <- grid.arrange(soilWaterPlot1, soilWaterPlot2, soilWaterPlot3, nrow = 3)

print(soilWaterPlot)

soilWaterPotential <- ggplot(data = soilWater[!is.na(soilWater$wpMA),],
                             aes(x = DT, y = wpMA, group = site)) +
  geom_line(size = 0.7) +
  scale_y_continuous(limits = c(-39,-7), expand = c(0,0)) +
  labs(x = "", y = "WP, 50 cm (kPa)") +
  theme_bw()
print(soilWaterPotential)
```

Sites where low flow studies have been done
```{r SiteMap}
siteLocations <- read.csv("Data/LowFlowSites.csv")

world <- ggplot() +
  borders("world", colour = "gray85", fill = "gray80", ylim = c(35,45), xlim = c(-125, -69)) +
  theme_map() 

Fig2 <- world + 
  geom_point(aes(x = Lon, y = Lat, color = Med),
             data = siteLocations, 
             size = 2) 


# +
  # scale_color_manual(values = c("Clouds" = "#7570B3", "Ice" = "#0233a6", "Incl" = "#66A61E", "NoVeg" = "#E7298A"))

Fig2
```

Representative hydrograph and all hydrographs
```{r Hydrographs}

#Plot one hydrograph
hydgrf <- allData %>% 
  filter(DATE > as.Date("2018-09-01") & DATE < as.Date("2019-09-30")) %>% 
  ggplot(aes(x = DATE, y = WS2)) +
  geom_line(color = "#2171b5", size = 1) +
  scale_x_date(breaks = seq(as.Date("2018-10-02"), as.Date("2019-09-02"), by="2 months"),
               expand = c(0,0),
               date_labels = "%b-%Y") +
  theme_few() +
  theme(axis.title = element_blank(),
        axis.text = element_text(size = 14))
print(hydgrf)

#Restructure data to plot all hydrographs over each other
allHydgrfs <- allData %>% 
  filter(WY >= 1988 & WY <= 2019) %>% 
  select(DATE, WS2, WY) %>% 
  mutate(DATE2 = case_when(
    month(DATE) %in% c(10,11,12) ~ ymd(format(DATE, "2099-%m-%d")),
    month(DATE) %in% c(1,2,3,4,5,6,7,8,9) ~ ymd(format(DATE, "2100-%m-%d")))) %>% 
  ggplot() +
  geom_line(aes(x = DATE2, y = WS2, group = WY), color = "#d9d9d9")

print(allHydgrfs)

#From Garett
summary.plot.swe = swe_fill %>% 
  filter(waterYear > "1998" & waterYear < "2019") %>% 
  group_by(SITECODE, wy.day) %>% 
  summarise(med.swe=median(SWE_DAY, na.rm=TRUE)) %>%
  ungroup()

swe_fill %>% 
  # filter(SITECODE %in% c("CENMET", "PRIMET", "UPLMET")) %>%
  filter(SITECODE %in% c("CENMET")) %>%
  filter(waterYear > "1998" & waterYear < "2019") %>% 
  mutate(snow.amt.cat=as.factor(case_when(
    waterYear %in% c(1999,2002,2008,2013,2017) ~ "High",
    waterYear %in% c(2003, 2005, 2010, 2014, 2015) ~ "Low",
    TRUE ~ "Average"
  ))) %>% 
  ggplot() +
  # geom_line(aes(x=wy.day, y=SWE_DAY, group=waterYear), color="gray") +
  geom_line(aes(x=wy.day, y=SWE_DAY, group=waterYear, color=snow.amt.cat)) +
  scale_color_manual(values=c("gray","#0081bd","#9c0505")) +
  geom_line(data=summary.plot.swe %>% filter(SITECODE %in% c("CENMET")),
            aes(x=wy.day, y=med.swe), color="black", linewidth=1) +
  # scale_x_date(expand=c(0,1), date_labels="%b", date_breaks="1 month") +
  # facet_grid(SITECODE~., scales="free") +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=expansion(mult=c(0,0.05))) +
  theme_bw() +
  theme(
    panel.background=element_rect(color="black"),  # change plot outline color
    strip.text=element_text(size=14, color="black"),  # facet text
    strip.background=element_rect(color=NA, fill=NA),  # facet background
    axis.text=element_text(size=10, color="black"),  # axis labels
    axis.title=element_text(size=12, color="black"), # axis title
    legend.text=element_text(size=12, color="black"),  # legend text
    legend.title=element_text(size=12, color="black"),  # legend title text
    legend.position="bottom"
  ) +
  labs(x="Water Year Day", y="Snow Water Equivalent (mm)", 
       color="")

```


































