---
title: "HJA_ET_fromMoore2004"
output: html_notebook
---

Attempts to leverage data from Moore et al 2004 study on transpiration at HJA WS1 and 2

Load data from digitized csvs
```{r Data}
Figure3aData <- read.csv("Data/Moore2004Data/Figure3a.csv")
Figure3bData <- read.csv("Data/Moore2004Data/Figure3b.csv")
Figure7Data <- read.csv("Data/Moore2004Data/Figure7.csv")
```

Restructure data:
- Make three df (sap flux 1999 and 2000 and transpiration)
- Lots of fiddling to get day of year into the right date
- Aggregate into daily values
- Linear interpolation of missing values

```{r structureData}
sapFlux1999 <- Figure3bData %>% 
  rename(sFlux = SapFluxDens) %>% 
  mutate(daysInYear = ifelse(leap_year(year), 366, 365)) %>% 
  mutate(decimalDate = year + DOY/daysInYear) %>% 
  mutate(dateTime = date_decimal(decimalDate)) %>% 
  mutate(DATE = as.Date(dateTime)) %>% 
  group_by(DATE, tree) %>% 
  summarise(sFluxDaily = mean(sFlux)) %>% 
  ungroup() %>% 
  spread(tree,sFluxDaily) %>% 
  padr::pad(interval = "day") %>% 
  mutate(PSMEy = na.approx(PSMEy),
         ALRUy = na.approx(ALRUy)) %>% 
  gather(tree, sFlux, PSMEy, ALRUy)
  

sapFlux2000 <- Figure3aData %>% 
  rename(sFlux = SapFluxDens) %>% 
  mutate(daysInYear = ifelse(leap_year(year), 366, 365)) %>% 
  mutate(decimalDate = year + DOY/daysInYear) %>% 
  mutate(dateTime = date_decimal(decimalDate)) %>% 
  mutate(DATE = as.Date(dateTime)) %>% 
  group_by(DATE, tree) %>% 
  summarise(sFluxDaily = mean(sFlux)) %>% 
  ungroup() %>% 
  spread(tree,sFluxDaily) %>% 
  padr::pad(interval = "day") %>% 
  mutate(PSMEy = na.approx(PSMEy),
         PSMEo = na.approx(PSMEo)) %>% 
  gather(tree, sFlux, PSMEy, PSMEo)
  
trans2000 <- Figure7Data %>% 
  mutate(daysInYear = ifelse(leap_year(year), 366, 365)) %>% 
  mutate(decimalDate = year + DOY/daysInYear) %>% 
  mutate(dateTime = date_decimal(decimalDate)) %>% 
  mutate(DATE = as.Date(dateTime)) %>% 
  group_by(DATE, tree) %>% 
  summarise(transDaily = mean(trans)) %>% 
  ungroup() %>% 
  spread(tree,transDaily) %>% 
  padr::pad(interval = "day") %>% 
  mutate(PSMEy = na.approx(PSMEy),
         PSMEo = na.approx(PSMEo)) %>% 
  gather(tree, trans, PSMEy, PSMEo)

#Plot these dfs to check how they match with Moore 2004
Figure3aMoore <- sapFlux2000 %>% 
  ggplot(aes(x = DATE, y = sFlux)) +
  geom_line(aes(color = tree))
print(Figure3aMoore)

Figure3bMoore <- sapFlux1999 %>%
  ggplot(aes(x = DATE, y = sFlux)) +
  geom_line(aes(color = tree))
print(Figure3bMoore)

Figure7Moore <- trans2000 %>% 
  ggplot(aes(x = DATE, y = trans)) +
  geom_line(aes(color = tree))
print(Figure7Moore)

```

