---
title: "HJA_Deficit"
output: html_notebook
---

Using WS1 and WS2 data to calculate flow deficits in WS1

```{r Packages}
library(tidyverse)
library(lubridate)
library(broom)
```

Regression calibrations based on monthly data
```{r MonthRegression}
CalStartWY = 1953
CalEndWY = 1961

CalData <- allData %>% 
  select(DATE, WY, WS1, WS2) %>% 
  arrange(DATE) %>% 
  filter(between(WY, CalStartWY, CalEndWY)) %>% 
  mutate(Month = month(DATE),
         Year = year(DATE)) %>%
  group_by(Year, Month) %>%
  summarise(WS1 = sum(WS1),
            WS2 = sum(WS2)) %>%
  ungroup()

CalReg <- CalData %>% 
  select(Month, WS1, WS2) %>% 
  nest(Data = -Month) %>% 
  mutate(Fit = map(Data, ~ lm(WS1 ~ WS2, data = .x))) %>% 
  mutate(RegPar = map(Fit, tidy)) %>% 
  unnest(RegPar) %>% 
  mutate(term = case_when(term == "(Intercept)" ~ "Int",
                          TRUE ~ "Slp")) %>% 
  select(Month, term, estimate) %>% 
  spread(term, estimate)

# Test <- CalData %>% 
#   select(Month, WS1, WS2) %>% 
#   filter(Month == 5) %>% 
#   lm(WS1 ~ WS2, data = .)
```

Select two time periods and compare monthly mean deficit/surplus
```{r PostVsPresent}
PostStartWY = 1967
PostEndWY = 1971
PresStartWY = 2015
PresEndWY = 2019

DefCompare <- allData %>% 
  select(DATE, WY, WS1, WS2) %>% 
  arrange(DATE) %>% 
  filter(between(WY, PostStartWY, PostEndWY) |
           between(WY, PresStartWY, PresEndWY)) %>% 
  mutate(Month = month(DATE),
         Year = year(DATE)) %>%
  group_by(Year, Month) %>% 
  summarise(WS1 = sum(WS1),
            WS2 = sum(WS2)) %>% 
  ungroup() %>% 
  mutate(Period = case_when(Year < 1980 ~ "Post",
                            Year > 1980 ~ "Pres")) %>% 
  merge(CalReg, by = "Month") %>% 
  mutate(WS1pred = WS2 * Slp + Int) %>% #Calculate predicted WS1 w/out treatment
  mutate(WS1def = WS1 - WS1pred) %>% #Calculate surplus or deficit
  arrange(Year, Month)
  
DefMonWS1 <- DefCompare %>% 
  select(Month, Period, WS1def) %>% 
  group_by(Period, Month) %>% 
  summarise(WS1def = mean(WS1def)) %>% 
  mutate(WYMonth = case_when(Month >= 10 ~ Month - 9,
                             Month < 10 ~ Month + 3)) %>% 
  arrange(Period, WYMonth) %>% 
  mutate(Month = factor(month.abb[Month], levels = c(month.abb[10:12], month.abb[1:9])))

DefMonWS1Plot <- DefMonWS1 %>% 
  ggplot(aes(x = Month, y = WS1def, fill = Period)) +
  geom_bar(position = "dodge", stat = "identity")
print(DefMonWS1Plot)

save(DefMonWS1, file = "ManuscriptDocuments/Figures/FigureData/WS1_Month_Deficit.RData")
```

Regression based on daily data
```{r DayRegression}
CalStartWY = 1953
CalEndWY = 1961

CalDataDaily <- allData %>% 
  select(DATE, WY, WS1, WS2) %>% 
  arrange(DATE) %>% 
  filter(between(WY, CalStartWY, CalEndWY)) %>% 
  filter(!(month(DATE) == 2 & day(DATE) == 29)) %>% 
  mutate(DoWY = rep(1:365, 9))

CalRegDaily <-CalDataDaily %>% 
  select(DoWY, WS1, WS2) %>% 
  nest(Data = -DoWY) %>% 
  mutate(Fit = map(Data, ~ lm(WS1 ~ WS2, data = .x))) %>% 
  mutate(RegPar = map(Fit, tidy)) %>% 
  unnest(RegPar) %>% 
  mutate(term = case_when(term == "(Intercept)" ~ "Int",
                          TRUE ~ "Slp")) %>% 
  select(DoWY, term, estimate) %>% 
  spread(term, estimate)
  
```

Compare Post and Present using daily regressions
```{r PostVsPresDaily}
PostStartWY = 1967
PostEndWY = 1971
PresStartWY = 2015
PresEndWY = 2019

DefCompareDaily <- allData %>% 
  select(DATE, WY, WS1, WS2) %>% 
  arrange(DATE) %>% 
  filter(between(WY, PostStartWY, PostEndWY) |
           between(WY, PresStartWY, PresEndWY)) %>% 
  mutate(Month = month(DATE),
         Year = year(DATE),
         Period = case_when(between(WY, PostStartWY, PostEndWY) ~ "Post",
                            between(WY, PresStartWY, PresEndWY) ~ "Pres")) %>% 
  group_by(Period, Month) %>% 
  summarise(WS1 = mean(WS1),
            WS2 = mean(WS2)) %>% 
  ungroup() %>% 
  merge(CalReg, by = "Month") %>% 
  mutate(WS1pred = WS2 * Slp + Int) %>% #Calculate predicted WS1 w/out treatment
  mutate(WS1def = WS1 - WS1pred) #Calculate surplus or deficit

```


















