---
title: "LowFlowData"
author: "Mallard"
date: "4/27/2023"
output: html_document
---

This file creates an annual low flow dataset for use in other analyses.

Calculate a 7-day low flow for all days and the same day every year in WS1,2,3,10. Same day is 7-day window centered on 8/30, doy = 242. 
Should add code to dynamically generate variable names from WS names!
```{r WSLowFlowAug}
WSLowFlowData <- allData %>% 
  select(DATE, precip, WS1, WS2, WS3, WS9, WS10, meanVpd, meanTemp, WY) %>% 
  mutate(WS1Low = rollmean(WS1, 7, fill = NA, na.rm = FALSE, align = "center"),
         WS2Low = rollmean(WS2, 7, fill = NA, na.rm = FALSE, align = "center"),
         WS3Low = rollmean(WS3, 7, fill = NA, na.rm = FALSE, align = "center"),
         WS9Low = rollmean(WS9, 7, fill = NA, na.rm = FALSE, align = "center"),
         WS10Low = rollmean(WS10, 7, fill = NA, na.rm = FALSE, align = "center"))

#Subsetting and plotting                            
# allData %>%
#   filter(DATE > mdy("1-01-1996") & DATE < mdy("12-01-1996")) %>%
#   ggplot(aes(DATE, WS3, color = "daily")) +
#   geom_line()

#Create annual aug low flow
#Discard before 1979 and after 2018 for incomplete data
WSLowFlowAnn <- WSLowFlowData %>% 
  mutate(Year = year(DATE)) %>% 
  group_by(Year) %>% 
  summarize(WS1minQAug = WS1Low[yday(DATE) == 242],
            WS2minQAug = WS2Low[yday(DATE) == 242],
            WS3minQAug = WS3Low[yday(DATE) == 242],
            WS9minQAug = WS9Low[yday(DATE) == 242],
            WS10minQAug = WS10Low[yday(DATE) == 242]) %>% 
  filter(Year > 1979 & Year < 2019)

#Plot all aug 30 low-flows
# WSLowFlowAnn %>% 
#   gather(WS,lowFlowAug,c("WS1minQAug","WS2minQAug","WS3minQAug","WS10minQAug")) %>% 
#   ggplot(aes(x = Year, y = lowFlowAug, fill = WS)) + geom_bar(position = "dodge", stat = "identity") + theme_classic()
# 
# WSLowFlowAnn %>% 
#   gather(WS,lowFlowAug,c("WS1minQAug","WS2minQAug","WS3minQAug","WS10minQAug")) %>% 
#   ggplot(aes(x = Year, y = lowFlowAug, color = WS)) + geom_line() + theme_classic()

```

Use allData to redo dataset for ws2 and add 7day mean low flow. Create annual time series from it
```{r ws2LowFlow}
#Find running 7 day mean
WS2data <- allData %>% 
  select(DATE, precip, WS2, WY) %>% 
  rename(Q = WS2) %>% 
  mutate(Low7Day = rollmean(Q,
                            7,
                            fill = NA,
                            na.rm = FALSE,
                            align = "center"))

# #Plot and subset to check data
WS2data %>%
  filter(DATE > mdy("4-01-1986") & DATE < mdy("11-01-1986")) %>%
  ggplot(aes(DATE, Q, color = "daily"))+
    geom_line()+
    geom_line(aes(x = DATE, y = Low7Day, color = "7 day mean"))

# testSubset<-WS2data %>%
#   filter(DATE > mdy("01-01-1987") & DATE < mdy("12-31-1987"))

#Create annual low flow, along with total precip and date of low flow, add precip for preceding WY
#Discard 1979 and 2018 for incomplete data
WS2LowFlow <- WS2data %>% 
  mutate(Year = year(DATE)) %>% 
  group_by(Year) %>% 
  summarize(minQ = min(Low7Day, na.rm = TRUE),
            minQDate = DATE[which.min(Low7Day)],
            annP = sum(precip, na.rm = TRUE)) %>% 
  mutate(minQDoy = yday(minQDate))

WS2WYprecip<- WS2data %>% 
  group_by(WY) %>% 
  summarize(annPWY = sum(precip, na.rm = TRUE))

WS2LowFlow$annPWY <- WS2WYprecip$annPWY

WS2LowFlow <- WS2LowFlow %>% 
  filter(Year != 1979 & Year != 2018)

#Some figures summarizing this annual dataset
WS2LowFlow %>% 
  ggplot(aes(y = minQ)) +
  geom_boxplot() +
  scale_x_discrete() +
  labs(y = "7 day min daily runoff (mm)")
WS2LowFlow %>% 
  ggplot(aes(x = Year, y = minQ)) +
  geom_bar(stat = 'identity') +
  labs(y = "7 day min daily runoff (mm)")

WS2LowFlow %>% 
  ggplot(aes(y = minQDoy)) +
  geom_boxplot() +
  scale_x_discrete() +
  labs(y = "7 day min day of year (mm)") 
WS2LowFlow %>% 
  ggplot(aes(x = Year, y = minQDoy)) +
  geom_bar(stat = 'identity') +
  labs(y = "7 day min day of year (mm)")

WS2LowFlow %>% 
  ggplot(aes(y = annPWY)) +
  geom_boxplot() +
  scale_x_discrete() +
  labs(y = "annual precip (mm)")
WS2LowFlow %>% 
  ggplot(aes(x = Year, y = annPWY)) +
  geom_bar(stat = 'identity') +
  labs(y = "annual precip (mm)")
  
#Figures comparing them
# ggplot(data = WS2LowFlow, aes(x = annP, y = minQ))+
#   geom_point()+
#    labs(x = "annual precip (mm)", y = "7 day min daily runoff (mm)")
ggplot(data = WS2LowFlow, aes(x = annPWY, y = minQ))+
  geom_point()+
   labs(x = "prior WY precip (mm)", y = "7 day min daily runoff (mm)")
ggplot(data = WS2LowFlow, aes(x = minQDoy, y = minQ))+
  geom_point()+
  labs(x = "7 day min day of year (mm)", y = "7 day min daily runoff (mm)")

```

Do the same for WS1
```{r ws1LowFlow}
#Find running 7 day mean
WS1data <- allData %>% 
  select(DATE, precip, WS1, WY) %>% 
  rename(Q = WS1) %>% 
  mutate(Low7Day = rollmean(Q,
                            7,
                            fill = NA,
                            na.rm = FALSE,
                            align = "center"))

# #Plot and subset to check data
# WS1data %>%
#   filter(DATE > mdy("4-01-1986") & DATE < mdy("11-01-1986")) %>%
#   ggplot(aes(DATE, Q, color = "daily"))+
#     geom_line()+
#     geom_line(aes(x = DATE, y = Low7Day, color = "7 day mean"))

# testSubset<-WS2data %>%
#   filter(DATE > mdy("01-01-1987") & DATE < mdy("12-31-1987"))

#Create annual low flow, along with total precip and date of low flow, add precip for preceding WY
#Discard 1979 and 2018 for incomplete data
WS1LowFlow <- WS1data %>% 
  mutate(Year = year(DATE)) %>% 
  group_by(Year) %>% 
  summarize(minQ = min(Low7Day, na.rm = TRUE),
            minQDate = DATE[which.min(Low7Day)],
            annP = sum(precip, na.rm = TRUE)) %>% 
  mutate(minQDoy = yday(minQDate))

WS1WYprecip<- WS1data %>% 
  group_by(WY) %>% 
  summarize(annPWY = sum(precip, na.rm = TRUE))

WS1LowFlow$annPWY <- WS1WYprecip$annPWY

WS1LowFlow <- WS1LowFlow %>% 
  filter(Year != 1979 & Year != 2018)

#Some figures summarizing this annual dataset
WS1LowFlow %>% 
  ggplot(aes(y = minQ)) +
  geom_boxplot() +
  scale_x_discrete() +
  labs(y = "7 day min daily runoff (mm)")
WS1LowFlow %>% 
  ggplot(aes(x = Year, y = minQ)) +
  geom_bar(stat = 'identity') +
  labs(y = "7 day min daily runoff (mm)")

WS1LowFlow %>% 
  ggplot(aes(y = minQDoy)) +
  geom_boxplot() +
  scale_x_discrete() +
  labs(y = "7 day min day of year (mm)") 
WS1LowFlow %>% 
  ggplot(aes(x = Year, y = minQDoy)) +
  geom_bar(stat = 'identity') +
  labs(y = "7 day min day of year (mm)")

WS1LowFlow %>% 
  ggplot(aes(y = annPWY)) +
  geom_boxplot() +
  scale_x_discrete() +
  labs(y = "annual precip (mm)")
WS1LowFlow %>% 
  ggplot(aes(x = Year, y = annPWY)) +
  geom_bar(stat = 'identity') +
  labs(y = "annual precip (mm)")
  
#Figures comparing them
# ggplot(data = WS2LowFlow, aes(x = annP, y = minQ))+
#   geom_point()+
#    labs(x = "annual precip (mm)", y = "7 day min daily runoff (mm)")
ggplot(data = WS1LowFlow, aes(x = annPWY, y = minQ))+
  geom_point()+
   labs(x = "prior WY precip (mm)", y = "7 day min daily runoff (mm)")
ggplot(data = WS1LowFlow, aes(x = minQDoy, y = minQ))+
  geom_point()+
  labs(x = "7 day min day of year (mm)", y = "7 day min daily runoff (mm)")
```


