---
title: "Low Flow Figures"
output:
  html_document:
    df_print: paged
---
Load packages
```{r packages, message=FALSE, echo=FALSE, warning=FALSE}
library(lubridate)
library(ggplot2)
library(zoo)
library(plotly)
library(ggpubr)
library(ggthemes)
library(tidyverse)
```

Common figure characteristics
```{r}
#File path to figure data
FigDataPath = "ManuscriptDocuments/Figures/FigureData/"

#Default text size
myTxtSz = 20
```

Figure 1: Conceptual model

Figure 2: Site map

Figure 3: Hydro and climate data
```{r Figure3-HydroAndClim}
#Load Data from HJA_ICRW8_figs
load(paste(FigDataPath,"ClimAndHydData.RData", sep = ""))

#Panel A: Precip Plot
Fig3a <- precipData %>% 
  mutate(WYMonth = c(4:12,1:3)) %>% 
  arrange(WYMonth) %>% 
  mutate(precipMonth = factor(month.abb[precipMonth], levels = c(month.abb[10:12], month.abb[1:9]))) %>% 
  ggplot() +
  geom_bar(aes(x = precipMonth, y = meanPrecip), fill = "steelblue", stat = "identity") +
  geom_errorbar(aes(x = precipMonth, ymin = lowPrecip, ymax = upPrecip),
                width = 0.2) +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  coord_cartesian(ylim = c(0, 500)) +
  theme_bw(base_size = 20) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) +
  labs(x = "", y = "Precip (mm/mon)")
print(Fig3a)

#Panel B: Hydrograph Plot
Fig3b <- ggplot() + 
  geom_line(data = allHydgrfData, aes(x = DATE2, y = WS2, group = WY), color = "#d9d9d9") +
  geom_line(data = meanHydgrfData, aes(x = DATE2, y = meanWS2), linewidth = 1.5, color = "#2b8cbe") +
  theme_bw(base_size = 20) + 
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) +
  labs(x = "", y = "Runoff (mm/d)") +
  scale_x_date(expand = c(0,0),
               date_labels = "%b") +
  scale_y_continuous(expand = c(0,0)) +
  coord_cartesian(ylim = c(-1, 160))
print(Fig3b)

#Panel B inset
Fig3bInset <- ggplot() +
  geom_line(data = allHydgrfData, aes(x = DATE2, y = WS2, group = WY), color = "#d9d9d9") +
  geom_line(data = meanHydgrfData, aes(x = DATE2, y = meanWS2), linewidth = 1.5, color = "#2b8cbe") +
  theme_bw(base_size = 40) + 
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) +
  labs(x = "", y = "") +
  scale_x_date(expand = c(0,0),
               date_labels = "%b") +
  scale_y_continuous(expand = c(0,0)) +
  coord_cartesian(xlim = as.Date(c("2100-06-01", "2100-09-30")),
                  ylim = c(0.1, 3))
print(Fig3bInset)

```

Figure 4: WS1 surplus and deficit 
```{r Figure4-Deficit}
#Load data from HJA_Deficit
load(paste(FigDataPath,"WS1_Month_Deficit.RData", sep = ""))

#Set colors
Post = "#1f78b4"
Pres1 = "#33a02c"
Pres2 = "#a6cee3"
Pres3 = "#fb9a99"
Pres4 = "#b2df8a"

myCols = c("Post" = Post, 
           "Pres1" = Pres1,
           "Pres2" = Pres2,
           "Pres3" = Pres3,
           "Pres4" = Pres4)

#Figure 4
Fig4a <- WS1QChange5YrMon %>% 
  ggplot(aes(x = Month, y = WS1dif, fill = Period)) +
  geom_bar(position = "dodge", stat = "identity") +
  geom_hline(yintercept = 0) +
  theme_bw(base_size = 18) + 
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) +
  labs(x = "", y = "\u0394 Runoff (mm/mon)") +
  scale_fill_manual(values = c(Post, Pres1, Pres2, Pres3, Pres4))
print(Fig4a)

Fig4b <- WS1QChange5YrMon %>% 
  ggplot(aes(x = Month, y = 100*(WS1dif/WS1pred), fill = Period)) +
  geom_bar(position = "dodge", stat = "identity") +
  geom_hline(yintercept = 0) +
  theme_bw(base_size = 18) + 
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank()) +
  labs(x = "", y = "% \u0394 Runoff") +
  scale_fill_manual(values = c(Post, Pres1, Pres2, Pres3, Pres4))
print(Fig4b)
```

Figure 5: Window analysis
```{r Figure5-ClimWin}
#Load Data from HJAClimWin
load(paste(FigDataPath,"ClimWinTile.RData", sep = ""))

#Add other days so that x axis expands
DateRangeModels <- data.frame(winDay = seq(ymd("2023/04/01"), ymd("2023/07/30"         )))

#Panel A and B together
Fig5 <- tileTopModels %>% 
  filter(WS != "WS3") %>% 
  ggplot(aes(x = winDay, y = WS, fill = nModDay)) +
  geom_tile() + facet_wrap(~ climVar) +
  theme_bw(base_size = myTxtSz) +
  labs(x = "Window open or close day",
       y = "",
       fill = "n(Win)"
       ) +
  scale_x_date(expand = c(0,0), date_labels = "%b %e")

print(Fig5)
```

Figure 6: Soil moisture/Riparian water table
```{r Figure6-SoilMoisture}
#Load Data from HJA_ICRW8_figs
load(paste(FigDataPath,"SoilWater.RData", sep = ""))

#Panel A: Hillslope soil moisture
Fig6a <- soilWater %>% 
  ggplot(aes(x = D, y = wp, group = site)) + 
  geom_line(size = 0.5, color = "steelblue") +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_date(date_labels = "%b", expand = c(0,0)) +
  coord_cartesian(ylim = c(-75, 0)) +
  labs(x = "", y = "WP, 50 cm (kPa)") +
  theme_bw(base_size = myTxtSz)
  
print(Fig6a)
```

Figure 7: Riparian Water Table

Figure 8: Transpiration deficit
```{r Figure8-TransDefFig}
#Load Data from HJA_ET_fromMoore2004
load(paste(FigDataPath,"TransDef.RData", sep = ""))
#Load Data from HJA_OpenET_WB
load(paste(FigDataPath,"OETMonthly.RData", sep = ""))

#Set colors
youngCol = "#4dac26"
oldCol = "#a6611a"
ripDefCol = "#01665e"
hillDefCol = "#80cdc1"
openETCol = "#bfbfbf"

myCols = c(c("Young" = youngCol, "Old" = oldCol, "HillDef" = hillDefCol, "RipDef" = ripDefCol, "ET_OET" = openETCol))

myLineWidth = 2
myTxtSz = 20

#Add OpenET estimates to TransDef and rescale OpenET estimates to hillslope and riparian areas (ha)
ATot = 96
ARip = 2.18
AHill = ATot - ARip

TransOET <- TransDef %>% 
  select(DATE, transHillOld, transHillYoung, transDefHill,
         transRipOld, transRipYoung, transDefRip) %>%
  mutate(ET_OpenET = 
    case_when(month(DATE) == 5 ~ WS1_All_OET_month$Mean_Month_ET[5],
              month(DATE) == 6 ~ WS1_All_OET_month$Mean_Month_ET[6],
              month(DATE) == 7 ~ WS1_All_OET_month$Mean_Month_ET[7],
              month(DATE) == 8 ~ WS1_All_OET_month$Mean_Month_ET[8],
              TRUE ~ 0)) %>% 
  mutate(ET_OET_Rip = ET_OpenET * ARip/ATot,
         ET_OET_Hill = ET_OpenET * AHill/ATot)

#Panel A: Hillslope Transpiration Deficit
Fig7a <- TransOET %>% 
  select(DATE, transHillOld, transHillYoung, transDefHill, ET_OET_Hill) %>% 
  ggplot() +
  geom_area(aes(x = DATE, y = transHillYoung, fill = "Young"), 
            alpha = 0.3) + 
  geom_area(aes(x = DATE, y = transHillOld, fill = "Old"), 
            alpha = 0.3) +
  geom_area(aes(x = DATE, y = transDefHill, fill = "HillDef"), 
            alpha = 0.7) +
   geom_area(aes(x = DATE, y = ET_OET_Hill, fill = "ET_OET"),
            alpha = 0.4) +
  theme_bw(base_size = myTxtSz) +
  scale_x_date(expand = c(0,0)) +
  labs(x = "", y = "Transpiration or ET (mm/d)") +
  scale_fill_manual(name = "", values = myCols)
print(HillslopeTransDefPlot)

#Panel B: Riparian Transpiration Deficit
Fig7b <- TransOET %>% 
  select(DATE, transRipOld, transRipYoung, transDefRip, ET_OET_Rip) %>% 
  ggplot() +
  geom_area(aes(x = DATE, y = transRipYoung, fill = "Young"), 
            alpha = 0.3) + 
  geom_area(aes(x = DATE, y = transRipOld, fill = "Old"), 
            alpha = 0.3) +
  geom_area(aes(x = DATE, y = transDefRip, fill = "RipDef"),
            alpha = 0.7) +
  geom_area(aes(x = DATE, y = ET_OET_Rip, fill = "ET_OET"),
            alpha = 0.4) +
  theme_bw(base_size = myTxtSz) +
  scale_x_date(expand = c(0,0)) +
  labs(x = "", y = "Transpiration or ET (mm/d)") +
  scale_fill_manual(name = "", values = myCols)
print(RiparianTransDefPlot)

#Panel C: Overall Transpiration Deficit
myCols = c(Rip = ripDefCol, Hill = hillDefCol)

Fig7c <- TransOET %>% 
  select(DATE, transDefRip, transDefHill) %>% 
  mutate(Rip = cumsum(transDefRip),
         Hill = cumsum(transDefHill)) %>% 
  select(-c(transDefRip, transDefHill)) %>% 
  gather(Position, sumTrans, Rip, Hill) %>% 
  ggplot(aes(x = DATE, y = sumTrans, fill = Position)) +
  geom_area(alpha = 0.7) +
  scale_fill_manual(name = "", values = myCols) +
  theme_bw(base_size = myTxtSz) +
  scale_x_date(expand = c(0,0)) +
  labs(x = "", y = "\u03A3 Transpiration (mm)")
print(OverallTransDefPlot)  

```

Figure 9: Conceptual model revisited

Table 1: Transpiration values
